name: Run Citellus analysis

on:
  push:
    branches:
      - master
  schedule:
    - cron:  '0 0 * * *'

jobs:
  citellus:
    runs-on: ubuntu-16.04
    steps:
    - uses: actions/checkout@v2

    # Use GitHub Actions' cache to shorten build times and decrease load on servers
    - uses: actions/cache@v2.1.1
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements/*') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - uses: citellusorg/gh-action-citellus@1.0
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        SOSREPORT: test
        CONFIGPATH: "./"
