name: Run Risu analysis

on:
  push:
    branches:
      - master
  schedule:
    - cron:  '0 0 * * *'

jobs:
  risu:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.4

    # Use GitHub Actions' cache to shorten build times and decrease load on servers
    - uses: actions/cache@v3.0.10
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements/*') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - uses: risuorg/gh-action-risu@1.0.4
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        SOSREPORT: test
        CONFIGPATH: "./"
